# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NoteEditor(object):
    def setupUi(self, NoteEditor):
        NoteEditor.setObjectName("NoteEditor")
        NoteEditor.setWindowModality(QtCore.Qt.WindowModal)
        NoteEditor.resize(315, 278)
        NoteEditor.setMinimumSize(QtCore.QSize(315, 278))
        NoteEditor.setMaximumSize(QtCore.QSize(315, 278))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        NoteEditor.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        NoteEditor.setFont(font)
        self.start_time_label = QtWidgets.QLabel(NoteEditor)
        self.start_time_label.setGeometry(QtCore.QRect(230, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_time_label.setFont(font)
        self.start_time_label.setObjectName("start_time_label")
        self.end_time_label = QtWidgets.QLabel(NoteEditor)
        self.end_time_label.setGeometry(QtCore.QRect(230, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.end_time_label.setFont(font)
        self.end_time_label.setObjectName("end_time_label")
        self.start_spinner = QtWidgets.QTimeEdit(NoteEditor)
        self.start_spinner.setGeometry(QtCore.QRect(230, 30, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_spinner.setFont(font)
        self.start_spinner.setObjectName("start_spinner")
        self.end_spinner = QtWidgets.QTimeEdit(NoteEditor)
        self.end_spinner.setGeometry(QtCore.QRect(230, 80, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.end_spinner.setFont(font)
        self.end_spinner.setObjectName("end_spinner")
        self.title_line_edit = QtWidgets.QLineEdit(NoteEditor)
        self.title_line_edit.setGeometry(QtCore.QRect(10, 10, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_line_edit.setFont(font)
        self.title_line_edit.setAccessibleDescription("")
        self.title_line_edit.setInputMask("")
        self.title_line_edit.setText("")
        self.title_line_edit.setMaxLength(500)
        self.title_line_edit.setClearButtonEnabled(True)
        self.title_line_edit.setObjectName("title_line_edit")
        self.description_text_panel = QtWidgets.QPlainTextEdit(NoteEditor)
        self.description_text_panel.setGeometry(QtCore.QRect(10, 40, 211, 231))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.description_text_panel.setFont(font)
        self.description_text_panel.setDocumentTitle("")
        self.description_text_panel.setObjectName("description_text_panel")
        self.delete_note_button = QtWidgets.QPushButton(NoteEditor)
        self.delete_note_button.setGeometry(QtCore.QRect(230, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.delete_note_button.setFont(font)
        self.delete_note_button.setObjectName("delete_note_button")
        self.save_button = QtWidgets.QPushButton(NoteEditor)
        self.save_button.setGeometry(QtCore.QRect(230, 168, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_button.setFont(font)
        self.save_button.setObjectName("save_button")
        self.change_date_button = QtWidgets.QPushButton(NoteEditor)
        self.change_date_button.setGeometry(QtCore.QRect(230, 190, 81, 41))
        self.change_date_button.setObjectName("change_date_button")
        self.important_check_box = QtWidgets.QCheckBox(NoteEditor)
        self.important_check_box.setGeometry(QtCore.QRect(230, 110, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.important_check_box.setFont(font)
        self.important_check_box.setObjectName("important_check_box")

        self.retranslateUi(NoteEditor)
        QtCore.QMetaObject.connectSlotsByName(NoteEditor)

    def retranslateUi(self, NoteEditor):
        _translate = QtCore.QCoreApplication.translate
        NoteEditor.setWindowTitle(_translate("NoteEditor", "Редактирование задачи"))
        self.start_time_label.setText(_translate("NoteEditor", "Начало"))
        self.end_time_label.setText(_translate("NoteEditor", "Окончание"))
        self.delete_note_button.setText(_translate("NoteEditor", "Удалить\n"
"заметку"))
        self.save_button.setText(_translate("NoteEditor", "Сохранить"))
        self.change_date_button.setText(_translate("NoteEditor", "Изменить\n"
"дату"))
        self.important_check_box.setText(_translate("NoteEditor", "Важно"))

